apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-p5
  labels:
    app: capstone-p5
  namespace: default
spec:
  progressDeadlineSeconds: 3600
  replicas: 3
  selector:
    matchLabels:
      app: capstone-p5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-p5
    spec:
      containers:
        - image: 773453802440.dkr.ecr.us-east-1.amazonaws.com/capstone-project5:latest
          imagePullPolicy: Always
          name: capstone-p5
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"
