apiVersion: v1
kind: Service
metadata:
  name: capstone-p5
  labels:
    app: capstone-p5
spec:
  type: LoadBalancer
  selector:
    app: capstone-p5
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
